spring.application.name=KafkaProducerApp

# см KafkaConfig.java
# -------------------

# Kafka Broker
# spring.kafka.bootstrap-servers=localhost:9093

# Kafka Consumer Configuration
# spring.kafka.consumer.group-id=person-consumer-group
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON Deserializer Settings
# spring.kafka.consumer.properties.spring.json.trusted.packages=*
