### 1) Получить список топиков
GET http://localhost:8082/topics

### 2) Отправка сообщения в топик "w8-topic" key=1 value= 'new Person(1, "Joe", "Doe")'
POST http://localhost:8082/topics/w8-topic
Content-Type: application/vnd.kafka.json.v2+json

{
  "records": [
    {
      "key": 1,
      "value": {
        "id": 1,
        "firstName": "Joe",
        "lastName": "Doe",
        "age": 32
      }
    }
  ]
}

### 3) Чтение сообщений из топика:
## 3.1) Создание консюмера с параметрами GROUP_ID = "my-consumer-group".
## В теле указывается: имя консюмера, формат, AUTO_OFFSET_RESET_CONFIG = "earliest" (начинает считывать сообщения с самого начала топика).
## В ответе - ссылка на созданный консюмер: "instance_id": "my-consumer"
##                                                         "base_uri": "http://kafka-rest:8082/consumers/my-consumer-group/instances/my-consumer".
POST http://localhost:8082/consumers/my-consumer-group
Content-Type: application/vnd.kafka.json.v2+json

{
  "name": "my-consumer", "format": "json", "auto.offset.reset": "earliest"
}

### 3.2) Подписка на топик. URL = 'ссылка из "base_uri" (п.3.2)' + '/subscription'
## Ожидаемый успешный ответ: '204 No Content'
POST http://localhost:8082/consumers/my-consumer-group/instances/my-consumer/subscription
Content-Type: application/vnd.kafka.json.v2+json

{
  "topics": [
    "w8-topic"
  ]
}

### 3.3) Чтение данных из топика. URL = 'ссылка из "base_uri" (п.3.2)' + '/records'
## Примечание: - первый запрос возвращает 'HTTP/1.1 200 OK' (без данных)
##             - второй запрос возвращает данные
GET http://localhost:8082/consumers/my-consumer-group/instances/my-consumer/records
Accept: application/vnd.kafka.json.v2+json

### 3.4) Перемещение оффсета в начало. URL = 'ссылка из "base_uri" (п.3.2)' + '/positions/beginning'
## Ожидаемый успешный ответ: '204 No Content'
POST http://localhost:8082/consumers/my-consumer-group/instances/my-consumer/positions/beginning
Content-Type: application/vnd.kafka.json.v2+json

{
  "partitions": [
    {
      "topic": "w8-topic",
      "partition": 0
    }
  ]
}

### 3.5) Удалить консюмер
DELETE http://localhost:8082/consumers/my-consumer-group/instances/my-consumer
Content-Type: application/vnd.kafka.json.v2+json
