spring.application.name=KafkaProducerApp

# см KafkaConfig.java
# -------------------

# Kafka Broker
# spring.kafka.bootstrap-servers=localhost:9093

# Kafka Producer Configuration
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
